language: python
cache:
- apt
- pijp
python:
- 3.5
addons:
  apt:
    packages:
    - graphviz
    - yui-compressor
install:
- pip install 'Nikola[extras]'
- pip install -r requirements.txt
script:
- nikola build
notifications:
  email: false