on:
  push:
    branches:
      - main

jobs:
  hugo_build:
    runs-on: ubuntu-latest
    name: "Build and deploy my Hugo site"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.131.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy site
        if: ${{ github.ref_name == 'main' }}
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -rav --delete
          path: public/
          remote_path: /var/www/virtual/flowfx/html/flowfx.de/
          remote_host: ariel.uberspace.de
          remote_user: flowfx
          remote_key: ${{ secrets.SSH_KEY }}
